### ISSUE TITLE
java11 运行报错

### ISSUE THREAD

**Issue by i11us0ry** [MaskCyberSecurityTeam/BurpHeaderHelper#3]
version:
java version "11.0.18" 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)

log:
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.fna.a(Unknown Source)
	at burp.fna.<init>(Unknown Source)
	at burp.fm9.a(Unknown Source)
	at burp.fl5.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by i11us0ry** [comment]
1.3.0的就可以

**Comment by Richard-Tang** [comment]
重新上传了 :)

**Comment by Strugg1e** [comment]
v1.3.1 jdk8也报类似错误:
java.lang.Exception: Extension class is not a recognized type
	at burp.zc5.H(Unknown Source)
	at burp.zc5.T(Unknown Source)
	at burp.m3w.y(Unknown Source)
	at burp.m_.P(Unknown Source)
	at burp.v8m.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
